// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	cassandrav1alpha1 "github.com/sky-uk/cassandra-operator/cassandra-operator/pkg/apis/cassandra/v1alpha1"
	versioned "github.com/sky-uk/cassandra-operator/cassandra-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/sky-uk/cassandra-operator/cassandra-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/sky-uk/cassandra-operator/cassandra-operator/pkg/client/listers/cassandra/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CassandraInformer provides access to a shared informer and lister for
// Cassandras.
type CassandraInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.CassandraLister
}

type cassandraInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCassandraInformer constructs a new informer for Cassandra type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCassandraInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCassandraInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCassandraInformer constructs a new informer for Cassandra type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCassandraInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1alpha1().Cassandras(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1alpha1().Cassandras(namespace).Watch(options)
			},
		},
		&cassandrav1alpha1.Cassandra{},
		resyncPeriod,
		indexers,
	)
}

func (f *cassandraInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCassandraInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *cassandraInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&cassandrav1alpha1.Cassandra{}, f.defaultInformer)
}

func (f *cassandraInformer) Lister() v1alpha1.CassandraLister {
	return v1alpha1.NewCassandraLister(f.Informer().GetIndexer())
}
