apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cassandras.core.sky.uk
spec:
  group: core.sky.uk
  names:
    kind: Cassandra
    listKind: CassandraList
    plural: cassandras
    singular: cassandra
  scope: Namespaced
  version: v1alpha1
