[[constraint]]
    name = "github.com/sky-uk/cassandra-operator"
    source = "github.com/wallrj/cassandra-operator"
    branch = "71-webhook"

[[constraint]]
  name = "github.com/openshift/generic-admission-server"
  version = "1.14.0"

[prune]
  go-tests = true
  unused-packages = true
