// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// CassandraListerExpansion allows custom methods to be added to
// CassandraLister.
type CassandraListerExpansion interface{}

// CassandraNamespaceListerExpansion allows custom methods to be added to
// CassandraNamespaceLister.
type CassandraNamespaceListerExpansion interface{}
