// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/sky-uk/cassandra-operator/cassandra-operator/pkg/apis/cassandra/v1alpha1"
	scheme "github.com/sky-uk/cassandra-operator/cassandra-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CassandrasGetter has a method to return a CassandraInterface.
// A group's client should implement this interface.
type CassandrasGetter interface {
	Cassandras(namespace string) CassandraInterface
}

// CassandraInterface has methods to work with Cassandra resources.
type CassandraInterface interface {
	Create(*v1alpha1.Cassandra) (*v1alpha1.Cassandra, error)
	Update(*v1alpha1.Cassandra) (*v1alpha1.Cassandra, error)
	UpdateStatus(*v1alpha1.Cassandra) (*v1alpha1.Cassandra, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Cassandra, error)
	List(opts v1.ListOptions) (*v1alpha1.CassandraList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Cassandra, err error)
	CassandraExpansion
}

// cassandras implements CassandraInterface
type cassandras struct {
	client rest.Interface
	ns     string
}

// newCassandras returns a Cassandras
func newCassandras(c *CoreV1alpha1Client, namespace string) *cassandras {
	return &cassandras{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the cassandra, and returns the corresponding cassandra object, and an error if there is any.
func (c *cassandras) Get(name string, options v1.GetOptions) (result *v1alpha1.Cassandra, err error) {
	result = &v1alpha1.Cassandra{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cassandras").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Cassandras that match those selectors.
func (c *cassandras) List(opts v1.ListOptions) (result *v1alpha1.CassandraList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.CassandraList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cassandras").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cassandras.
func (c *cassandras) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("cassandras").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a cassandra and creates it.  Returns the server's representation of the cassandra, and an error, if there is any.
func (c *cassandras) Create(cassandra *v1alpha1.Cassandra) (result *v1alpha1.Cassandra, err error) {
	result = &v1alpha1.Cassandra{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("cassandras").
		Body(cassandra).
		Do().
		Into(result)
	return
}

// Update takes the representation of a cassandra and updates it. Returns the server's representation of the cassandra, and an error, if there is any.
func (c *cassandras) Update(cassandra *v1alpha1.Cassandra) (result *v1alpha1.Cassandra, err error) {
	result = &v1alpha1.Cassandra{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cassandras").
		Name(cassandra.Name).
		Body(cassandra).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *cassandras) UpdateStatus(cassandra *v1alpha1.Cassandra) (result *v1alpha1.Cassandra, err error) {
	result = &v1alpha1.Cassandra{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cassandras").
		Name(cassandra.Name).
		SubResource("status").
		Body(cassandra).
		Do().
		Into(result)
	return
}

// Delete takes name of the cassandra and deletes it. Returns an error if one occurs.
func (c *cassandras) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cassandras").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cassandras) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cassandras").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched cassandra.
func (c *cassandras) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Cassandra, err error) {
	result = &v1alpha1.Cassandra{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("cassandras").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
