#!/usr/bin/env bash
set -e

snapshots_file=/tmp/snapshots

if [ "$1" = "version" ]; then
    echo "ReleaseVersion: 3.11"
elif [ "$1" = "status" ]; then
    echo "UN ${NODE_LISTEN_ADDRESS}"
elif [ "$1" = "snapshot" ]; then
    snapshot_name=$3
    shift 3
    keyspace_list=$@
    if [ -z "${keyspace_list}" ]; then
        keyspace_list="system_auth system_traces system_distributed"
        echo "Requested creating snapshot(s) for [all keyspaces] with snapshot name [$snapshot_name]"
    else
        echo "Requested creating snapshot(s) for [$(echo ${keyspace_list} | sed 's/ /, /g')] with snapshot name [$snapshot_name]"
    fi

    for keyspace in ${keyspace_list}; do
        echo "${snapshot_name} ${keyspace} mytable 0 bytes 0 bytes" >> ${snapshots_file}
    done
elif [ "$1" = "listsnapshots" ]; then
    if [ -e ${snapshots_file} ]; then
        cat ${snapshots_file}
    else
        echo "There are no snapshots"
    fi
elif [ "$1" = "clearsnapshot" ]; then
    snapshot_name=$3
    keyspace=$5
    if [ -n "${keyspace}" ]; then
        if [ -e ${snapshots_file} ]; then
            sed -i "/$snapshot_name $keyspace /d" ${snapshots_file}
        fi
    else
        rm -f ${snapshots_file}
    fi
fi
